"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Sias Mey"
email = "siasmey@gmail.com"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519.pub"

[ui]
default-command = ["log", "--revisions", "ancestors(@) & mutable()"]
paginate = "never"
diff-editor = ":builtin"
diff-formatter = ["difft", "--color=always", "$left", "$right"]
merge-editor = "mergiraf"
