"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Sias Mey"
email = "sias.mey@hpe.com"

[ui]
default-command = ["log", "--revisions", "ancestors(@) & mutable()"]
paginate = "never"
diff-editor = ":builtin"
diff-formatter = ["difft", "--color=always", "$left", "$right"]
merge-editor = "mergiraf"

[template-aliases]
'log_pr_summary' = '''" - "++self.description().first_line()++"\n"'''

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519.pub"

[aliases]
pr-summary = [
  "log",
  "--no-graph",
  "-r",
  "..@ & mutable()",
  "-T",
  "log_pr_summary",
]
