"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Sias Mey"
email = "sias.mey@hpe.com"

[ui]
default-command = ["log", "--revisions", "ancestors(@) & mutable()"]
paginate = "never"
dif-editor = ":builtin"

[template-aliases]
'log_pr_summary' = '''" - "++self.description().first_line()++"\n"'''

[aliases]
pr-summary = [
  "log",
  "--no-graph",
  "-r",
  "..@ & mutable()",
  "-T",
  "log_pr_summary",
]
